// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppContent: typeof import('./src/components/AppContent.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CorpReLoginDialog: typeof import('./src/components/CorpReLoginDialog.vue')['default']
    CustomDialog: typeof import('./src/components/CustomDialog.vue')['default']
    DeleteDialog: typeof import('./src/components/DeleteDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FindPwdSteps: typeof import('./src/components/FindPwdSteps.vue')['default']
    FindResetPassword: typeof import('./src/components/FindResetPassword.vue')['default']
    ForgetAndSendEmail: typeof import('./src/components/ForgetAndSendEmail.vue')['default']
    ForgetPassword: typeof import('./src/components/ForgetPassword.vue')['default']
    HttpButton: typeof import('./src/components/HttpButton.vue')['default']
    NewFooter: typeof import('./src/components/NewFooter.vue')['default']
    NewHeader: typeof import('./src/components/NewHeader.vue')['default']
    OIcon: typeof import('./src/components/OIcon.vue')['default']
    ReLoginDialog: typeof import('./src/components/ReLoginDialog.vue')['default']
    ReTryDialog: typeof import('./src/components/ReTryDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignReLoginDialog: typeof import('./src/components/SignReLoginDialog.vue')['default']
    SignSuccessDialog: typeof import('./src/components/SignSuccessDialog.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
}
